name: Auto Commit Twice Daily

on:
  schedule:
    - cron: "0 5 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update File
        run: echo "# Updated on $(date)" >> auto_varghese.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add auto_varghese.py
          git commit -m "Auto update $(date)" || echo "No changes"
          git push
